name: Release System

permissions:
  contents: write

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    # Extract version from release tag 
    - name: Extract version
      id: extract_version
      uses: battila7/get-version-action@v2

    # Substitute the Manifest and Download URLs in the system.json
    - name: Substitute Manifest and Download Links For Versioned Ones
      id: sub_manifest_link_version
      uses: cschleiden/replace-tokens@v1
      with:
        files: 'system.json'
      env:
        version: ${{steps.extract_version.outputs.version}}
        url: https://github.com/${{github.repository}}
        manifest: https://github.com/${{github.repository}}/releases/latest/download/system.json
        download: https://github.com/${{github.repository}}/releases/download/${{github.event.release.tag_name}}/system.zip

    # Create a zip file with all the system's files
    - run: zip -r ./system.zip system.json README.md LICENSE *.css *.js lang/ scripts/ styles/ templates/ packs/

    # Create a release for this specific version
    - name: Update Release with Files
      id: create_version_release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true # Set this to false if you want to prevent updating existing releases
        name: ${{ github.event.release.name }}
        draft: ${{ github.event.release.draft }}
        prerelease: ${{ github.event.release.prerelease }}
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: './system.json, ./system.zip'
        tag: ${{ github.event.release.tag_name }}
        body: ${{ github.event.release.body }}